export const recipeData = [
  {
    id: 1,
    title: "Classic Margherita Pizza",
    description: "A simple yet delicious pizza with fresh tomatoes, mozzarella, and basil.",
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=500&h=300&fit=crop",
    category: "Italian",
    difficulty: "Medium",
    cookingTime: "45",
    servings: 4,
    rating: 4.8,
    featured: true,
    dietary: ["Vegetarian"],
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Fresh mozzarella",
      "Fresh basil leaves",
      "Olive oil",
      "Salt",
      "Black pepper"
    ],
    instructions: [
      "Preheat oven to 475°F (245°C)",
      "Roll out pizza dough on floured surface",
      "Spread tomato sauce evenly",
      "Add torn mozzarella pieces",
      "Bake for 12-15 minutes until golden",
      "Top with fresh basil before serving"
    ],
    nutritionInfo: {
      calories: 320,
      protein: 14,
      carbs: 42,
      fat: 12,
      fiber: 3
    },
    tags: ["pizza", "italian", "vegetarian", "dinner"],
    author: "Chef Maria",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z"
  },
  {
    id: 2,
    title: "Chocolate Chip Cookies",
    description: "Soft and chewy chocolate chip cookies that are perfect for any occasion.",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&h=300&fit=crop",
    category: "Desserts",
    difficulty: "Easy",
    cookingTime: "25",
    servings: 24,
    rating: 4.9,
    featured: false,
    dietary: ["Vegetarian"],
    ingredients: [
      "All-purpose flour",
      "Baking soda",
      "Salt",
      "Butter",
      "Brown sugar",
      "White sugar",
      "Eggs",
      "Vanilla extract",
      "Chocolate chips"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C)",
      "Mix flour, baking soda, and salt in bowl",
      "Cream butter and sugars until fluffy",
      "Beat in eggs and vanilla",
      "Gradually mix in flour mixture",
      "Stir in chocolate chips",
      "Drop rounded tablespoons on baking sheet",
      "Bake 9-11 minutes until golden brown"
    ],
    nutritionInfo: {
      calories: 180,
      protein: 2,
      carbs: 26,
      fat: 8,
      fiber: 1
    },
    tags: ["cookies", "dessert", "chocolate", "baking"],
    author: "Chef Sarah",
    createdAt: "2024-01-10T10:30:00Z",
    updatedAt: "2024-01-10T10:30:00Z"
  },
  {
    id: 3,
    title: "Grilled Chicken Salad",
    description: "Fresh and healthy grilled chicken salad with mixed greens and vegetables.",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&h=300&fit=crop",
    category: "Salads",
    difficulty: "Easy",
    cookingTime: "20",
    servings: 2,
    rating: 4.6,
    featured: true,
    dietary: ["Gluten-Free", "High-Protein"],
    ingredients: [
      "Chicken breast",
      "Mixed greens",
      "Cherry tomatoes",
      "Cucumber",
      "Red onion",
      "Olive oil",
      "Lemon juice",
      "Salt",
      "Black pepper",
      "Garlic powder"
    ],
    instructions: [
      "Season chicken breast with salt, pepper, and garlic powder",
      "Grill chicken for 6-8 minutes per side",
      "Let chicken rest for 5 minutes, then slice",
      "Combine mixed greens, tomatoes, cucumber, and onion",
      "Make dressing with olive oil and lemon juice",
      "Top salad with sliced chicken and dressing"
    ],
    nutritionInfo: {
      calories: 280,
      protein: 35,
      carbs: 8,
      fat: 12,
      fiber: 4
    },
    tags: ["salad", "healthy", "protein", "low-carb"],
    author: "Chef Mike",
    createdAt: "2024-01-12T14:15:00Z",
    updatedAt: "2024-01-12T14:15:00Z"
  },
  {
    id: 4,
    title: "Beef Tacos",
    description: "Authentic Mexican-style beef tacos with fresh toppings.",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=500&h=300&fit=crop",
    category: "Mexican",
    difficulty: "Medium",
    cookingTime: "30",
    servings: 4,
    rating: 4.7,
    featured: false,
    dietary: ["Gluten-Free"],
    ingredients: [
      "Ground beef",
      "Corn tortillas",
      "Onion",
      "Garlic",
      "Cumin",
      "Chili powder",
      "Paprika",
      "Salt",
      "Lettuce",
      "Tomatoes",
      "Cheese",
      "Sour cream"
    ],
    instructions: [
      "Cook ground beef in skillet over medium heat",
      "Add diced onion and garlic, cook until soft",
      "Season with cumin, chili powder, paprika, and salt",
      "Warm tortillas in dry skillet",
      "Fill tortillas with beef mixture",
      "Top with lettuce, tomatoes, cheese, and sour cream"
    ],
    nutritionInfo: {
      calories: 420,
      protein: 28,
      carbs: 32,
      fat: 20,
      fiber: 5
    },
    tags: ["tacos", "mexican", "beef", "dinner"],
    author: "Chef Carlos",
    createdAt: "2024-01-08T16:45:00Z",
    updatedAt: "2024-01-08T16:45:00Z"
  },
  {
    id: 5,
    title: "Vegetable Stir Fry",
    description: "Quick and colorful vegetable stir fry with a savory sauce.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=300&fit=crop",
    category: "Asian",
    difficulty: "Easy",
    cookingTime: "15",
    servings: 3,
    rating: 4.4,
    featured: true,
    dietary: ["Vegetarian", "Vegan", "Gluten-Free"],
    ingredients: [
      "Mixed vegetables",
      "Bell peppers",
      "Broccoli",
      "Carrots",
      "Soy sauce",
      "Garlic",
      "Ginger",
      "Sesame oil",
      "Vegetable oil",
      "Green onions"
    ],
    instructions: [
      "Heat oil in wok or large skillet",
      "Add garlic and ginger, stir-fry for 30 seconds",
      "Add harder vegetables first (carrots, broccoli)",
      "Add softer vegetables (bell peppers)",
      "Stir in soy sauce and sesame oil",
      "Garnish with green onions before serving"
    ],
    nutritionInfo: {
      calories: 160,
      protein: 6,
      carbs: 18,
      fat: 8,
      fiber: 6
    },
    tags: ["stir-fry", "vegetarian", "healthy", "quick"],
    author: "Chef Lin",
    createdAt: "2024-01-14T12:00:00Z",
    updatedAt: "2024-01-14T12:00:00Z"
  },
  {
    id: 6,
    title: "Pancakes",
    description: "Fluffy American-style pancakes perfect for breakfast.",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=300&fit=crop",
    category: "Breakfast",
    difficulty: "Easy",
    cookingTime: "20",
    servings: 4,
    rating: 4.8,
    featured: false,
    dietary: ["Vegetarian"],
    ingredients: [
      "All-purpose flour",
      "Sugar",
      "Baking powder",
      "Salt",
      "Milk",
      "Eggs",
      "Butter",
      "Vanilla extract"
    ],
    instructions: [
      "Mix dry ingredients in large bowl",
      "Whisk wet ingredients in separate bowl",
      "Combine wet and dry ingredients until just mixed",
      "Heat griddle or pan over medium heat",
      "Pour batter to form pancakes",
      "Cook until bubbles form, then flip",
      "Cook until golden brown on both sides"
    ],
    nutritionInfo: {
      calories: 250,
      protein: 8,
      carbs: 38,
      fat: 8,
      fiber: 2
    },
    tags: ["pancakes", "breakfast", "fluffy", "american"],
    author: "Chef Emma",
    createdAt: "2024-01-09T07:30:00Z",
    updatedAt: "2024-01-09T07:30:00Z"
  },
  {
    id: 7,
    title: "Caesar Salad",
    description: "Classic Caesar salad with homemade dressing and croutons.",
    image: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=500&h=300&fit=crop",
    category: "Salads",
    difficulty: "Medium",
    cookingTime: "25",
    servings: 4,
    rating: 4.5,
    featured: false,
    dietary: ["Vegetarian"],
    ingredients: [
      "Romaine lettuce",
      "Parmesan cheese",
      "Bread cubes",
      "Anchovies",
      "Garlic",
      "Lemon juice",
      "Olive oil",
      "Egg yolk",
      "Dijon mustard",
      "Worcestershire sauce"
    ],
    instructions: [
      "Make croutons by toasting bread cubes with oil",
      "Whisk together dressing ingredients",
      "Wash and chop romaine lettuce",
      "Toss lettuce with dressing",
      "Top with croutons and Parmesan",
      "Serve immediately"
    ],
    nutritionInfo: {
      calories: 220,
      protein: 8,
      carbs: 12,
      fat: 16,
      fiber: 3
    },
    tags: ["salad", "classic", "caesar", "italian"],
    author: "Chef Antonio",
    createdAt: "2024-01-11T11:20:00Z",
    updatedAt: "2024-01-11T11:20:00Z"
  },
  {
    id: 8,
    title: "Banana Bread",
    description: "Moist and delicious banana bread made with ripe bananas.",
    image: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=300&fit=crop",
    category: "Desserts",
    difficulty: "Easy",
    cookingTime: "70",
    servings: 12,
    rating: 4.7,
    featured: true,
    dietary: ["Vegetarian"],
    ingredients: [
      "Ripe bananas",
      "All-purpose flour",
      "Sugar",
      "Baking soda",
      "Salt",
      "Butter",
      "Eggs",
      "Vanilla extract",
      "Walnuts (optional)"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C)",
      "Mash bananas in large bowl",
      "Mix in melted butter, sugar, egg, and vanilla",
      "Combine dry ingredients separately",
      "Fold dry ingredients into wet mixture",
      "Pour into greased loaf pan",
      "Bake for 60-65 minutes until golden"
    ],
    nutritionInfo: {
      calories: 195,
      protein: 3,
      carbs: 32,
      fat: 7,
      fiber: 2
    },
    tags: ["banana", "bread", "dessert", "baking"],
    author: "Chef Rachel",
    createdAt: "2024-01-13T09:45:00Z",
    updatedAt: "2024-01-13T09:45:00Z"
  }
];